version: '3'
services:
  sim:
    image: ghcr.io/eclipse-muto/multi-agent-sim:humble
    environment:
      - ROS_DOMAIN_ID=42
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true 
    depends_on:
      - novnc
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"
    networks:
      - x11

  racer1:
    image: ghcr.io/eclipse-muto/racecar:humble
    environment:
      - MUTONS=racecar1
      - ROS_DOMAIN_ID=42
    volumes:
      - ./samples/racer1/racer.yaml:/home/muto/install/racecar/share/racecar/config/muto.yaml
      - ./samples/racer1/gap.yaml:/home/muto/install/reactive_gap_follower/share/reactive_gap_follower/config/params.yaml
    networks:
      - x11
    depends_on:
      - sim

  racer2:
    image: ghcr.io/eclipse-muto/racecar:humble
    environment:
      - MUTONS=racecar2
      - ROS_DOMAIN_ID=42
    volumes:
      - ./samples/racer2/racer.yaml:/home/muto/install/racecar/share/racecar/config/muto.yaml
      - ./samples/racer2/gap.yaml:/home/muto/install/reactive_gap_follower/share/reactive_gap_follower/config/params.yaml
    networks:
      - x11
    depends_on:
      - sim

networks:
  x11:
