#
#  Copyright (c) 2023 Composiv.ai
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# and Eclipse Distribution License v1.0 which accompany this distribution.
#
# Licensed under the  Eclipse Public License v2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# The Eclipse Public License is available at
#    http://www.eclipse.org/legal/epl-v20.html
# and the Eclipse Distribution License is available at
#   http://www.eclipse.org/org/documents/edl-v10.php.
#
# Contributors:
#    Composiv.ai - initial API and implementation
#
#

/**:
  ros__parameters:
    twin_url: "http://ditto:ditto@sandbox.composiv.ai"
    anonymous: false
    namespace: org.eclipse.muto.sandbox
    name: gap-follower-racecar-01
    type: real_car
    attributes: '{"brand": "Traxxas", "model": "Slash 4x4"}'
    stack_topic: "stack"
    twin_topic: "twin"

    agent_to_gateway_topic: "agent_to_gateway"
    gateway_to_agent_topic: "gateway_to_agent"

    agent_to_commands_topic: "agent_to_command"
    commands_to_agent_topic: "command_to_agent"

/**/mqtt_gateway:
  ros__parameters:
    host: sandbox.composiv.ai # subject to change
    port: 1883
    keep_alive: 60
    user: null
    password: null
    namespace: org.eclipse.muto.sandbox
    

/**/commands_plugin:
  ros__parameters:
    commands:
      command1:
        name: ros/topic
        service: rostopic_list
        plugin: CommandPlugin

      command2:
        name: ros/topic/info
        service: rostopic_info
        plugin: CommandPlugin

      command3:
        name: ros/topic/echo
        service: rostopic_echo
        plugin: CommandPlugin

      command4:
        name: ros/node
        service: rosnode_list
        plugin: CommandPlugin

      command5:
        name: ros/node/info
        service: rosnode_info
        plugin: CommandPlugin

      command6:
        name: ros/param
        service: rosparam_list
        plugin: CommandPlugin

      command7:
        name: ros/param/get
        service: rosparam_get
        plugin: CommandPlugin


/**/muto_composer:
  ros__parameters:
    nav_topic: /nav
    pipelines:
      - name:  start
        pipeline:
          - sequence:
            - service: muto_compose
              plugin: ComposePlugin
            - service: muto_start_stack
              plugin: ComposePlugin
        compensation:
          - service: muto_kill_stack
            plugin: ComposePlugin   
      - name:  kill
        pipeline:
          - sequence:
            - service: muto_compose
              plugin: ComposePlugin
            - service: muto_kill_stack
              plugin: ComposePlugin
        compensation:
          - service: muto_kill_stack
            plugin: ComposePlugin 
      - name:  apply
        pipeline:
          - sequence:
            - service: muto_compose
              plugin: ComposePlugin
            - service: muto_apply_stack
              plugin: ComposePlugin
        compensation:
          - service: muto_kill_stack
            plugin: ComposePlugin 
    mqtt:
      host: sandbox.composiv.ai # subject to change
      port: 1883
      keep_alive: 60
      user: none
      password: none
    thing:
      namespace: org.eclipse.muto.sandbox # subject to change
      anonymous: False  # Use this for automatically generated id (uuid based)
      #   if anonymous is True or anynoymous param is missing, name/id will be auto generated
