/**/cass_gap_follower_slow_pace:
 ros__parameters:
  racecar_namespace: "racecar1"
  # Ranges Smoothing Filter Size
  # Dimension: 1 x (2*smoothing_filter_size-1)
  smoothing_filter_size: 1

  # Wall Follow PID controller gains

  # 2.45 radians 140 degrees (-70  >  +70)
  forward_view_angle: 2.0

  #rpilidar front index different than hokuyo
  scanner_forward_offsetangle: 0.0

  disparity_threshold: 0.3
  disparity_filter_size: 3
  disparity_publish: true
  car_width: 0.40

  # Desired Car Velocity based on Error
  error_based_ranges.low: 1.0
  error_based_ranges.medium: 3.0
  error_based_ranges.high: 6.0
  error_based_velocities.low: 1.0
  error_based_velocities.medium: 1.5
  error_based_velocities.high: 2.0

  drive_topic: "drive"  # notice that namespaces differ for each racecar so you don't have to change drive and scan topics
  scan_topic: "scan"

/**/cass_gap_follower_medium_pace:
 ros__parameters:
  racecar_namespace: "racecar1"
  smoothing_filter_size: 1
  forward_view_angle: 2.0
  scanner_forward_offsetangle: 0.0
  disparity_threshold: 0.3
  disparity_filter_size: 3
  disparity_publish: true
  car_width: 0.40
  error_based_ranges.low: 1.0
  error_based_ranges.medium: 3.0
  error_based_ranges.high: 6.0
  error_based_velocities.low: 2.0
  error_based_velocities.medium: 3.0
  error_based_velocities.high: 4.0

  drive_topic: "drive"
  scan_topic: "scan"

/**/cass_gap_follower_fast_pace:
 ros__parameters:
  racecar_namespace: "racecar1"
  smoothing_filter_size: 1
  forward_view_angle: 2.0
  scanner_forward_offsetangle: 0.0
  disparity_threshold: 0.3
  disparity_filter_size: 3
  disparity_publish: true
  car_width: 0.40
  error_based_ranges.low: 1.0
  error_based_ranges.medium: 3.0
  error_based_ranges.high: 6.0
  error_based_velocities.low: 2.0
  error_based_velocities.medium: 4.0
  error_based_velocities.high: 7.0
  drive_topic: "drive"
  scan_topic: "scan"
